[[redirects]]
  from = "/api"
  to = "https://icotest.iate.inra.fr/MyChoice/arguments?project=VITAMIN"
  status = 301
  force = true


# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"